
services:
  backend:
    build: ./backend
    container_name: webtube-backend
    ports:
      - "8080:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dlsauwebtubedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_PASSWORD: gjgtlenfknuevnuw
      OPENAI_API_KEY: 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
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: webtube-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: webtube-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dlsauwebtubedb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
